const main=document.querySelector('main'), feedback=document.querySelector('#feedback');
const state={library:null,source:null,selected:new Set(),view:'library'};
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
function message(text,error=false){feedback.textContent=text;feedback.className=error?'error':'';}
async function api(path, options={}){const init={...options};if(init.body && !(init.body instanceof FormData)){init.headers={'Content-Type':'application/json',...init.headers};init.body=JSON.stringify(init.body);}const r=await fetch(path,init);if(!r.ok){let data;try{data=await r.json();}catch{data={detail:`Request failed (${r.status})`};}throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));}return r.json();}
function button(text,action,cls=''){const b=el('button',text,cls);b.type='button';b.onclick=()=>run(action,b);return b;}
async function run(fn,b){if(b)b.disabled=true;main.setAttribute('aria-busy','true');message('Working…');try{await fn();if(feedback.textContent==='Working…')message('');}catch(e){message(e.message,true);}finally{if(b)b.disabled=false;main.removeAttribute('aria-busy');}}
function field(label,name,kind='input',value=''){const l=el('label',label),i=el(kind);i.name=name;if(kind==='textarea')i.rows=4;i.value=value;l.append(i);return [l,i];}
function select(label,values,current='',multiple=false){const [l,s]=field(label,label,'select');s.multiple=multiple;for(const [id,name] of values){const o=el('option',name);o.value=id;o.selected=Array.isArray(current)?current.includes(id):id===current;s.append(o);}return [l,s];}
function form(onSubmit){const f=el('form');f.onsubmit=e=>{e.preventDefault();run(()=>onSubmit(new FormData(f)),f.querySelector('[type=submit]'));};return f;}
function submit(text){const b=el('button',text,'primary');b.type='submit';return b;}
function heading(kicker,title,description){main.replaceChildren(el('div',kicker,'kicker'),el('h1',title),el('p',description,'intro'));}
function card(title,description){const c=el('section',undefined,'card');c.append(el('h3',title));if(description)c.append(el('p',description));return c;}
function actions(...buttons){const d=el('div',undefined,'actions');d.append(...buttons);return d;}
function detail(title,...nodes){const d=el('details');d.append(el('summary',title),...nodes);return d;}
function list(items){const u=el('ul');for(const item of items)u.append(el('li',item));return u;}
async function navigate(view){state.view=view;for(const b of document.querySelectorAll('nav button')){if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}await views[view]();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>run(()=>navigate(b.dataset.view),b));
async function libraries(){const data=await api('/libraries');return data.items;}
async function sourceItems(){return (await api('/sources'+(state.library?'?library_id='+encodeURIComponent(state.library):''))).items;}
async function libraryView(){heading('01 / COLLECT','A home for your knowledge.','Bring your sources together, extract their useful ideas, and keep the evidence close.');const libs=await libraries();const [l,s]=select('Current library',[['','All libraries'],...libs.map(l=>[l.id,l.name])],state.library||'');s.onchange=()=>{state.library=s.value||null;state.source=null;state.selected.clear();run(libraryView);};main.append(l);
 const create=form(async fd=>{const lib=await api('/libraries',{method:'POST',body:{name:fd.get('name'),description:fd.get('description')}});state.library=lib.id;await libraryView();message('Library created.');});for(const [label,name] of [['Library name','name'],['Description','description']]){const [l,i]=field(label,name);i.required=name==='name';create.append(l);}create.append(submit('Create library'));main.append(detail('Create a library',create));
 const sources=await sourceItems(),grid=el('div',undefined,'grid');for(const s of sources){const c=card(s.title,s.author||'Your source');c.append(el('span',s.processing_status.replaceAll('_',' '),'badge'),actions(button('Open source',()=>sourceView(s.id))));grid.append(c);}main.append(grid);if(!sources.length)main.append(el('p','No sources yet. Add a file below to begin.','empty'));
 const add=form(async fd=>{const source=await api('/sources',{method:'POST',body:{library_id:fd.get('Library'),title:fd.get('title'),author:fd.get('author'),source_type:'document'}});const file=fd.get('file');try{if(file?.size){const upload=new FormData();upload.append('file',file);await api(`/sources/${source.id}/upload`,{method:'POST',body:upload});}}catch(e){await sourceView(source.id);throw e;}await sourceView(source.id);message('Source added. Extract its text to continue.');});const c=card('Add a source','PDF, EPUB, Word, TXT, Markdown, HTML, CSV or JSON · up to 25 MB');const [ll,ss]=select('Library',libs.map(l=>[l.id,l.name]),state.library||libs[0]?.id);ss.required=true;add.append(ll);for(const [label,name] of [['Title','title'],['Author / creator','author'],['Source file','file']]){const [l,i]=field(label,name);i.required=name!=='author';if(name==='file'){i.type='file';i.accept='.pdf,.epub,.docx,.txt,.md,.html,.htm,.csv,.json';}add.append(l);}add.append(submit('Add source'));c.append(add);main.append(c);}
async function sourceView(id){state.source=id;const source=await api(`/sources/${id}`);heading('SOURCE / '+source.processing_status.replaceAll('_',' '),source.title,'Work in small interpretation batches. Progress is saved after each completed chunk.');main.append(actions(button('← Library',()=>navigate('library')),button('Extract & chunk',async()=>{await api(`/sources/${id}/process`,{method:'POST'});await sourceView(id);message('Text extracted and chunks ready.');},'primary')));
 if(!source.file_path){const upload=form(async fd=>{const data=new FormData();data.append('file',fd.get('file'));await api(`/sources/${id}/upload`,{method:'POST',body:data});await sourceView(id);});const [l,i]=field('Upload source file','file');i.type='file';i.required=true;upload.append(l,submit('Upload'));main.append(upload);}
 if(source.chunks_path){const [audit,chunks]=await Promise.all([api(`/sources/${id}/audit`),api(`/sources/${id}/chunks`)]);const p=audit.interpretation;const c=card('Interpretation',`${p.completed_chunks} of ${p.total_chunks} chunks complete · ${audit.asset_count} active assets · ${audit.knowledge_unit_count} consolidated units`);const progress=el('progress');progress.max=p.total_chunks||1;progress.value=p.completed_chunks;progress.setAttribute('aria-label','Interpretation progress');c.append(progress);if(source.stopped_reason)c.append(el('p',source.stopped_reason));c.append(actions(button('Interpret next chunk with Gemini',async()=>{const r=await api(`/sources/${id}/interpret?max_chunks=1`,{method:'POST'});await sourceView(id);message(r.stopped_reason||`${r.processed_this_run} chunk completed.`,!!r.stopped_reason);},'primary'),button('Browse knowledge',()=>{state.source=id;return navigate('knowledge');})));main.append(c);
 const auditCard=card('Quality & recovery',`Overlap: ${Math.round(audit.overlap_rate*100)}% · Superseded: ${audit.superseded_assets.length} · Old schema: ${audit.old_schema_assets.length}`);auditCard.append(list([`Missing evidence: ${audit.missing_evidence.length}`,`Missing keywords: ${audit.missing_keywords.length}`,`Evidence needing human review: ${audit.evidence_needing_review.length}`,`Asset types: ${Object.entries(audit.asset_types).map(([k,v])=>`${k} ${v}`).join(', ')||'None yet'}`,`Confidence scores: ${Object.entries(audit.confidence_distribution).map(([k,v])=>`${k}/5: ${v}`).join(', ')||'None yet'}`]),el('p',audit.note,'muted'));for(const job of audit.jobs.filter(j=>['failed','running'].includes(j.status))){auditCard.append(el('p',`${job.chunk_id}: ${job.status} — ${job.error||'Processing'}`),button('Recover job',async()=>{await api(`/knowledge-extractions/${job.id}/recover`,{method:'POST'});await sourceView(id);}));}main.append(detail('Source audit and recovery',auditCard));
 const manual=form(async fd=>{const chunkId=fd.get('Chunk');const job=(await api('/knowledge-extractions',{method:'POST',body:{source_id:id,chunk_id:chunkId,reprocess:fd.get('replace')==='on'}})).job;const raw=fd.get('result').trim();if(raw){let parsed;try{parsed=JSON.parse(raw);}catch{throw new Error('Paste valid extraction JSON with an assets array.');}await api(`/knowledge-extractions/${job.id}/results`,{method:'POST',body:parsed});await sourceView(id);message('Knowledge imported and validated.');}else{const req=await api(`/knowledge-extractions/${job.id}/request`);download(`${job.id}-prompt.json`,JSON.stringify(req,null,2),'application/json');message('Extraction prompt downloaded. Return here to import the structured result.');}});const [cl,cs]=select('Chunk',chunks.items.map(c=>[c.id,`Chunk ${c.chunk_index} · ${c.word_count} words${c.chapter_or_section?' · '+c.chapter_or_section:''}`]));manual.append(cl);const [rl,ri]=field('Structured extraction result (leave empty to download prompt)','result','textarea');manual.append(rl);const [pl,pi]=field('Intentionally replace this chunk’s active knowledge','replace');pi.type='checkbox';pl.className='check';manual.append(pl,submit('Download prompt / import result'));main.append(detail('Manual extraction or intentional reprocessing',el('p','Use your own structured response without an API call. Existing active knowledge is replaced only after validation succeeds.','muted'),manual));
 }
 main.append(actions(button('Delete source & derived output histories',async()=>{if(!confirm('Delete this source, its uploaded file, all extracted knowledge, and every saved output history containing its knowledge? This cannot be undone.'))return;await api(`/sources/${id}?delete_outputs=true`,{method:'DELETE'});state.selected.clear();state.source=null;await libraryView();message('Source and derived records deleted.');},'danger')));}
function download(name,text,type='text/plain'){const a=el('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function knowledgeView(){heading('02 / CONNECT','Ideas you can put to work.','Browse consolidated knowledge, inspect its evidence, and select the ideas you want to apply.');const sources=await sourceItems();const [l,s]=select('Source',[['','All sources'],...sources.map(s=>[s.id,s.title])],state.source||'');const [ql,qi]=field('Search knowledge','q');const search=form(async()=>render());search.append(l,ql,submit('Search'));main.append(search);const results=el('div',undefined,'grid');main.append(actions(button('Use selected knowledge →',()=>navigate('workshop'),'primary')),results);
 async function render(){state.source=s.value||null;let items;if(qi.value.trim().length>=2){const q=new URLSearchParams({q:qi.value,consolidated:'true'});if(s.value)q.set('source_id',s.value);if(state.library)q.set('library_id',state.library);items=(await api('/knowledge-assets/search?'+q)).items;}else if(s.value){items=(await api(`/sources/${s.value}/knowledge-units`)).items;}else{const batches=await Promise.all(sources.map(s=>api(`/sources/${s.id}/knowledge-units`)));items=batches.flatMap(b=>b.items);}results.replaceChildren();for(const g of items){const a=g.canonical_asset,c=card(a.title,a.what_it_says);c.append(el('span',`${a.asset_type.replaceAll('_',' ')} · ${g.support_count} supporting assets`,'badge'));const [l,i]=field('Use in Workshop',a.id);i.type='checkbox';i.checked=state.selected.has(a.id);l.className='check';i.onchange=()=>{if(i.checked)state.selected.add(a.id);else state.selected.delete(a.id);};c.append(l);const trail=g.evidence_trail.map(e=>el('p',`${sources.find(s=>s.id===e.source_id)?.title||e.source_id} · ${e.chunk_id}\n${e.evidence}`,'evidence'));c.append(detail('Evidence & provenance',...trail));results.append(c);}if(!items.length)results.append(el('p','No matching knowledge yet. Interpret a source, or try a different search.','empty'));}await render();}
async function workshopView(){heading('03 / APPLY','What are you working on?','Start with a real situation. Turn relevant knowledge into something useful, with source claims and design choices kept separate.');const [sourceData,mods,libs]=await Promise.all([api('/sources'),api('/outputs/modes'),libraries()]);const sources=sourceData.items;const f=form(async()=>{const payload=brief();const r=await api('/workshops/generate',{method:'POST',body:payload});await outputView(r.saved_output.id);message(r.quality_report?.validation_status==='failed'?'Saved as a draft with timing errors. Review the quality report before use.':r.quality_report?.validation_status==='needs_review'?'Saved as a draft. Some timing or source-rule checks need review.':'Generated and saved as version 1. Human review is still required.');});const container=card('Your brief');for(const [label,name,kind] of [['Situation','situation','textarea'],['Goal','goal','input'],['Audience','audience','input'],['Constraints — one per line','constraints','textarea'],['Tone / style','tone_or_style','input']]){const [l,i]=field(label,name,kind);i.required=['situation','goal'].includes(name);if(i.required)i.minLength=2;f.append(l);}const [ml,mode]=select('Output type',mods.items.map(m=>[m.id,m.label]));const [ll,lib]=select('Library scope',[['','All libraries'],...libs.map(l=>[l.id,l.name])],state.library||'');const [sl,ss]=select('Sources — optional; use Ctrl / Command to select several',sources.map(s=>[s.id,s.title]),state.source?[state.source]:[],true);function syncSources(){for(const o of ss.options){const show=!lib.value||sources.find(s=>s.id===o.value)?.library_id===lib.value;o.hidden=!show;o.disabled=!show;if(!show)o.selected=false;}}lib.onchange=()=>{syncSources();state.selected.clear();message('Library scope changed; explicit knowledge selection cleared.');};syncSources();f.append(ml,ll,sl,el('p',`${state.selected.size} explicitly selected knowledge units. Clear selection to use automatic retrieval.`,'muted'),button('Clear knowledge selection',()=>{state.selected.clear();return workshopView();}));
 function brief(){const fd=new FormData(f);return {situation:fd.get('situation'),goal:fd.get('goal'),audience:fd.get('audience')||null,constraints:fd.get('constraints').split('\n').filter(Boolean),tone_or_style:fd.get('tone_or_style')||null,output_type:mode.value,source_ids:[...ss.selectedOptions].map(o=>o.value),library_id:lib.value||null,asset_ids:[...state.selected],save:true};}
 const preview=el('div');f.append(actions(button('Preview relevant knowledge',async()=>{if(!f.reportValidity())return;const r=await api('/workshops/prepare',{method:'POST',body:brief()});preview.replaceChildren(el('h2',`${r.knowledge_unit_count} relevant knowledge units`));for(const g of r.knowledge_units)preview.append(el('p',`${g.canonical_asset.title} · ${g.source_ids.length} source(s)`));const s=r.synthesis_context;preview.append(el('p',`${s.agreements.length} candidate agreements · ${s.tensions.length} possible tensions`,'muted'));for(const t of s.tensions)preview.append(el('p',`${t.reason} ${t.asset_ids.join(', ')}`));preview.append(el('p',s.limitations,'muted'));}),submit('Generate & save')));container.append(f,preview);main.append(container);
 const manual=form(async fd=>{if(!f.reportValidity())return;let output;try{output=JSON.parse(fd.get('output'));}catch{throw new Error('Paste valid structured output JSON.');}const r=await api('/outputs',{method:'POST',body:{brief:brief(),output}});await outputView(r.id);});const [ol,oi]=field('Structured output result','output','textarea');oi.required=true;manual.append(ol,submit('Validate & save manual output'));main.append(detail('Manual output import',el('p','For existing structured outputs: title, output_type, content, applied_knowledge (asset_id and usage_note), and design_choices. Only retrieved assets can be cited.','muted'),manual));}
async function savedView(){heading('04 / KEEP','Work worth coming back to.','Every saved revision has its own record. Your original work and its knowledge context stay intact.');const data=await api('/outputs'),grid=el('div',undefined,'grid');const roots=new Map();for(const o of data.items)if(!roots.has(o.root_output_id))roots.set(o.root_output_id,o);for(const o of roots.values()){const c=card(o.title,`${o.output_type.replaceAll('_',' ')} · Version ${o.version}`);c.append(el('p',new Date(o.created_at).toLocaleString(),'muted'),button('Open output',()=>outputView(o.id)));grid.append(c);}main.append(grid);if(!data.count)main.append(el('p','Your saved work will appear here. Start in Workshop to create the first output.','empty'));}
async function outputView(id){const o=await api(`/outputs/${id}`);const quality=await api(`/outputs/${id}/quality`);heading('OUTPUT / VERSION '+o.version,o.title,`${o.output_type.replaceAll('_',' ')} · ${o.provider==='manual'?'Manually supplied or edited':o.provider+' / '+o.model} · Saved ${new Date(o.created_at).toLocaleString()}`);const review=card('Quality review',quality.validation_status.replaceAll('_',' '));review.append(el('p',quality.note),list(quality.issues.map(i=>i.message)));if(quality.timing_checks)review.append(list(quality.timing_checks.map(c=>`${c.criterion.replaceAll('_',' ')}: ${c.status} · Requested: ${c.requested_minutes??'unknown'} min · Calculated: ${c.calculated_minutes??'unknown'} min`)));main.append(review);const exportLink=el('a','Export Markdown');exportLink.href=`/outputs/${id}/export`;main.append(actions(button('← Saved outputs',()=>navigate('outputs')),exportLink),el('article',o.content,'reading'),el('h2','Applied knowledge'));for(const ref of o.applied_knowledge){const g=o.knowledge_snapshot.find(g=>g.canonical_asset.id===ref.asset_id);const c=card(g?.canonical_asset.title||ref.asset_id,ref.usage_note);c.append(detail('Source evidence',...(g?.evidence_trail||[]).map(e=>el('p',`${e.source_id} · ${e.chunk_id}\n${e.evidence}`,'evidence'))));main.append(c);}main.append(el('h2','Design choices'),list(o.design_choices.length?o.design_choices:['No additional design choices recorded. Review before use.']));
 const revise=form(async fd=>{const body={instruction:fd.get('instruction')};if(fd.get('manual')==='on'){body.content=fd.get('content');body.title=fd.get('title');body.design_choices=fd.get('choices').split('\n').filter(Boolean);}const n=await api(`/outputs/${id}/revise`,{method:'POST',body});await outputView(n.id);message(`Saved version ${n.version}; the original is unchanged.`);});const [il,ii]=field('Revision instruction','instruction');ii.required=true;ii.minLength=2;const [ml,mi]=field('Save my manual edits (no AI call)','manual');mi.type='checkbox';mi.checked=true;ml.className='check';const [tl,ti]=field('Title','title','input',o.title),[cl,ci]=field('Edited content','content','textarea',o.content),[dl,di]=field('Design choices — one per line','choices','textarea',o.design_choices.join('\n'));ci.rows=12;revise.append(il,ml,tl,cl,dl,submit('Save new version'));main.append(detail('Revise this output',revise));const history=await api(`/outputs/${id}/history`),h=card('Version history');const diff=el('pre');for(const v of history.items)h.append(actions(button(`Open version ${v.version}`,()=>outputView(v.id)),v.id!==id?button(`Compare v${o.version} → v${v.version}`,async()=>{const r=await api(`/outputs/${id}/compare/${v.id}`);diff.textContent=`Changed: ${r.changed_fields.join(', ')||'None'}\n\n${r.content_diff}`;}):el('span','Current','badge')));h.append(diff);main.append(h,actions(button('Delete entire output history',async()=>{if(!confirm('Delete this output and every revision? This cannot be undone.'))return;await api(`/outputs/${id}?entire_history=true`,{method:'DELETE'});await savedView();},'danger')));}
async function settingsView(){heading('05 / CONTROL','Your data, in your hands.','This beta runs locally for one owner. Keep backups private: they contain your uploaded sources and saved work.');const [usage,integrity]=await Promise.all([api('/usage'),api('/data/integrity')]);const c=card('AI usage',`${usage.calls_today} / ${usage.daily_call_limit} local daily call budget used`);c.append(list([`Gemini key: ${usage.configured?'Configured':'Not configured'}`,`Free-project confirmation: ${usage.free_tier_confirmed?'Confirmed':'Required before AI calls'}`,`State: ${usage.paused?'Paused':'Ready for explicit requests'}`]),el('p',usage.reason||usage.note,'muted'));if(usage.paused&&!usage.daily_limit_reached)c.append(button('Resume after quota reset',async()=>{await api('/usage/resume',{method:'POST'});await settingsView();}));const e=el('a','Download complete private backup');e.href='/data/export';const data=card('Export & integrity',integrity.ok?'No broken record links or missing source files detected.':`${integrity.issues.length} integrity issue(s) require attention.`);data.append(e,list(integrity.issues.map(i=>`${i.id}: ${i.problem}`)));main.append(c,data);}
const views={library:libraryView,knowledge:knowledgeView,workshop:workshopView,outputs:savedView,settings:settingsView};
run(()=>navigate('library'));
