'use strict';
const $ = (s) => document.querySelector(s);
const state = {libraries: [], sources: [], source: null, chunks: [], selected: new Set(), units: [], workshop: null, dirty: false};
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(message, error=false) { const el=$('#notice'); el.textContent=message; el.hidden=false; el.classList.toggle('error', error); }
async function api(path, options={}) {
  const response=await fetch(path, {...options, headers: options.body instanceof FormData ? {} : {'Content-Type':'application/json'}, cache:'no-store'});
  if(!response.ok) { const body=await response.json().catch(()=>({})); throw new Error(typeof body.detail==='string' ? body.detail : body.detail ? body.detail.map(e=>`${e.loc.join('.')}: ${e.msg}`).join('; ') : `Request failed (${response.status})`); }
  if(response.status===204) return null;
  return (response.headers.get('content-type')||'').includes('application/json') ? response.json() : response.text();
}
const post=(path,body)=>api(path,{method:'POST',body:JSON.stringify(body)});
async function run(button, fn) { if(button)button.disabled=true; try { await fn(); } catch(e) { notice(e.message,true); } finally { if(button)button.disabled=false; } }
function switchView(view) { document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==view); document.querySelectorAll('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view===view)); if(view==='knowledge')run(null,loadKnowledge); if(view==='workshop'){selectionCount();run(null,loadWorkshops);} }
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
function selectionCount() { const text=`${state.selected.size} approved idea${state.selected.size===1?'':'s'} selected`; $('#selected-count').textContent=text+' for workshop'; $('#workshop-selection').textContent=text+'. You can combine ideas from different sources.'; }
async function loadLibraries(selected) { const response=await api('/libraries'); state.libraries=response.items; $('#library-select').innerHTML=state.libraries.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('')||'<option value="">Create your first library</option>'; if(selected)$('#library-select').value=selected; $('#upload-form button').disabled=!state.libraries.length; await loadSources(); }
async function loadSources() { const id=$('#library-select').value; state.sources=id?(await api('/sources?library_id='+encodeURIComponent(id))).items:[]; $('#source-count').textContent=`${state.sources.length} source${state.sources.length===1?'':'s'}`; $('#source-list').innerHTML=state.sources.map(s=>`<button class="source-item ${state.source?.id===s.id?'active':''}" data-source="${esc(s.id)}">${esc(s.title)}<small>${esc(s.author||'Author not specified')} · ${esc(s.processing_status.replaceAll('_',' '))}</small></button>`).join(''); document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>run(b,()=>openSource(b.dataset.source))); }
$('#library-select').onchange=()=>run(null,async()=>{state.source=null;$('#source-detail').innerHTML='<h2>Select a source</h2><p>Upload a source or choose one from this library.</p>';await loadSources();});
$('#new-library').onclick=()=>$('#library-dialog').showModal(); $('#cancel-library').onclick=()=>$('#library-dialog').close();
$('#library-form').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const l=await post('/libraries',{name:$('#library-name').value,description:$('#library-description').value});$('#library-dialog').close();e.target.reset();await loadLibraries(l.id);notice('Library created. You can add your first source.');});};
$('#upload-form').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const file=$('#source-file').files[0]; if(!file)throw new Error('Choose a file.');if(file.size>25*1024*1024)throw new Error('Please choose a file smaller than 25 MB.');const s=await post('/sources',{library_id:$('#library-select').value,title:$('#source-title').value,author:$('#source-author').value});const form=new FormData();form.append('file',file);try{await api(`/sources/${s.id}/upload`,{method:'POST',body:form});}catch(error){await api(`/sources/${s.id}`,{method:'DELETE'}).catch(()=>{});throw error;}e.target.reset();await openSource(s.id);notice('Source uploaded. Process it to prepare the passages.');});};
async function openSource(id) {
  state.source=await api('/sources/'+id); const s=state.source;
  state.chunks=s.chunks_path?(await api(`/sources/${id}/chunks`)).items:[];
  $('#source-detail').classList.remove('empty');
  $('#source-detail').innerHTML=`<p class="eyebrow">SOURCE WORKSPACE</p><h2>${esc(s.title)}</h2><p class="quiet">${esc(s.author)} · ${esc(s.file_name||'No file uploaded')}</p><span class="badge">${esc(s.processing_status.replaceAll('_',' '))}</span><div class="actions"><button id="process-source" ${!s.file_name?'disabled':''}>${state.chunks.length?'Reprocess text':'Process source'}</button><button id="delete-source" class="danger">Delete source</button></div>${state.chunks.length?`<hr><h3>Extract reusable knowledge</h3><p class="hint">Choose a passage and copy its extraction prompt to your AI assistant. Paste the JSON response below. Imported ideas stay pending until you review them.</p><label>Passage<select id="chunk-select">${state.chunks.map((c,i)=>`<option value="${i}">Passage ${c.chunk_index} · ${c.word_count} words</option>`).join('')}</select></label><div id="passage" class="passage"></div><div class="actions"><button id="get-prompt" class="secondary">Get extraction prompt</button></div><form id="import-form"><label>AI response<textarea id="import-json" rows="7" required placeholder='{"units": [...]}' spellcheck="false"></textarea></label><button type="submit">Import for review</button></form>`:'<p class="hint">Processing extracts readable text and divides it into passages. AI analysis happens in the next step.</p>'}`;
  $('#process-source').onclick=e=>run(e.target,async()=>{notice('Extracting text and preparing passages…');await post(`/sources/${id}/process`,{});await openSource(id);notice('Passages are ready for knowledge extraction.');});
  $('#delete-source').onclick=e=>run(e.target,async()=>{if(!confirm('Delete this source, its uploaded file, and extracted knowledge?'))return;await api('/sources/'+id,{method:'DELETE'});state.source=null;$('#source-detail').innerHTML='<h2>Source deleted</h2>';await loadSources();await loadKnowledge();});
  if(state.chunks.length) { const show=()=>$('#passage').textContent=state.chunks[Number($('#chunk-select').value)].text; $('#chunk-select').onchange=show; show(); $('#get-prompt').onclick=e=>run(e.target,async()=>showPrompt('Extraction prompt',await api(`/sources/${id}/prompts/${state.chunks[Number($('#chunk-select').value)].id}`)));
    $('#import-form').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{let text=$('#import-json').value.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');let value;try{value=JSON.parse(text);}catch{throw new Error('The response is not valid JSON. Paste the complete JSON object from your AI assistant.');} if(Array.isArray(value.units)&&value.units.length===0){notice('This passage returned no reusable knowledge. Try another passage.');return;}const result=await post(`/sources/${id}/knowledge`,value);$('#import-json').value='';notice(`${result.count} ideas imported. Review them in the Knowledge tab.`);switchView('knowledge');});};
  } await loadSources();
}
function showPrompt(title,text){$('#prompt-title').textContent=title;$('#prompt-text').value=text;$('#prompt-dialog').showModal();}
$('#close-prompt').onclick=()=>$('#prompt-dialog').close();$('#copy-prompt').onclick=e=>run(e.target,async()=>{try{await navigator.clipboard.writeText($('#prompt-text').value);notice('Prompt copied.');}catch{$('#prompt-text').select();notice('Select and copy the highlighted prompt.');}});
async function loadKnowledge() {
  const params=new URLSearchParams({q:$('#knowledge-search').value,status:$('#review-filter').value});state.units=(await api('/knowledge?'+params)).items;
  const approved=(await api('/knowledge?status=approved')).items;const approvedIds=new Set(approved.map(u=>u.id));state.selected=new Set([...state.selected].filter(id=>approvedIds.has(id)));selectionCount();
  const sources=(await api('/sources')).items;const names=Object.fromEntries(sources.map(s=>[s.id,s.title]));
  $('#knowledge-list').innerHTML=state.units.map(u=>`<article class="knowledge-card"><span class="badge ${esc(u.status)}">${esc(u.status)}</span><p class="eyebrow">${esc(u.knowledge_type.replaceAll('_',' '))}</p><h2>${esc(u.title)}</h2><p>${esc(u.insight)}</p>${u.problem_solved?`<p><strong>Problem:</strong> ${esc(u.problem_solved)}</p>`:''}${u.when_to_use?`<p><strong>Use when:</strong> ${esc(u.when_to_use)}</p>`:''}${u.when_not_to_use?`<p><strong>Limits:</strong> ${esc(u.when_not_to_use)}</p>`:''}${u.steps.length?`<ol>${u.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>`:''}<blockquote>${esc(u.evidence)}</blockquote><p class="quiet">${esc(names[u.source_id])}<br>${esc(u.chunk_id)}</p><div class="actions">${u.status!=='approved'?`<button data-review="${esc(u.id)}" data-status="approved">Approve</button>`:''}${u.status!=='rejected'?`<button class="secondary" data-review="${esc(u.id)}" data-status="rejected">Reject</button>`:''}${u.status!=='pending'?`<button class="secondary" data-review="${esc(u.id)}" data-status="pending">Reopen review</button>`:''}</div>${u.status==='approved'?`<label class="check"><input type="checkbox" data-select="${esc(u.id)}" ${state.selected.has(u.id)?'checked':''}> Use in workshop</label>`:''}</article>`).join('')||'<div class="panel empty"><h2>No matching knowledge yet.</h2><p>Process a source and import its extracted ideas, or change your search filters.</p></div>';
  document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>run(b,async()=>{await api(`/knowledge/${b.dataset.review}/review`,{method:'PATCH',body:JSON.stringify({status:b.dataset.status})});await loadKnowledge();}));document.querySelectorAll('[data-select]').forEach(c=>c.onchange=()=>{c.checked?state.selected.add(c.dataset.select):state.selected.delete(c.dataset.select);selectionCount();});
}
$('#knowledge-search').onchange=()=>run(null,loadKnowledge);$('#review-filter').onchange=()=>run(null,loadKnowledge);$('#to-workshop').onclick=()=>{if(!state.selected.size)return notice('Select at least one approved idea first.',true);switchView('workshop');};
async function loadWorkshops(){const items=(await api('/workshops')).items;$('#workshop-list').innerHTML=items.map(w=>`<button class="saved-item" data-workshop="${esc(w.id)}">${esc(w.title)}<small>${esc(w.output_type)} · ${new Date(w.updated_at).toLocaleDateString()}</small></button>`).join('')||'<p class="quiet">Your saved work will appear here.</p>';document.querySelectorAll('[data-workshop]').forEach(b=>b.onclick=()=>run(b,async()=>{if(state.dirty&&!confirm('Discard unsaved changes and open another workshop?'))return;await openWorkshop(b.dataset.workshop);}));}
$('#workshop-form').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{if(!state.selected.size)throw new Error('Select approved ideas in the Knowledge tab first.');if(state.dirty&&!confirm('Discard unsaved changes and create another workshop?'))return;const w=await post('/workshops',{title:$('#workshop-title').value,goal:$('#workshop-goal').value,output_type:$('#output-type').value,knowledge_ids:[...state.selected]});await openWorkshop(w.id);await loadWorkshops();notice('Evidence brief created and saved.');});};
async function openWorkshop(id){const w=await api('/workshops/'+id);state.workshop=w;state.dirty=false;$('#workshop-detail').classList.remove('empty');$('#workshop-detail').innerHTML=`<p class="eyebrow">EDITABLE OUTPUT</p><h2>${esc(w.title)}</h2><p class="quiet" id="save-state">Saved</p><label>Output<textarea id="output-editor" class="editor" spellcheck="true"></textarea></label><div class="actions"><button id="save-output">Save changes</button><button id="workshop-prompt" class="secondary">Get workshop prompt</button><button id="export-output" class="secondary">Export Markdown</button><button id="delete-workshop" class="danger">Delete</button></div><details><summary>Source evidence (${w.evidence.length})</summary>${w.evidence.map((u,i)=>`<div class="evidence-item"><strong>[${i+1}] ${esc(u.title)}</strong><p>${esc(u.evidence)}</p><p class="quiet">${esc(u.source_title)} · ${esc(u.chunk_id)}</p></div>`).join('')}</details>`;$('#output-editor').value=w.content;$('#output-editor').oninput=()=>{state.dirty=true;$('#save-state').textContent='Unsaved changes';};$('#save-output').onclick=e=>run(e.target,saveOutput);$('#workshop-prompt').onclick=e=>run(e.target,async()=>showPrompt('Workshop prompt',await api(`/workshops/${id}/prompt`)));$('#export-output').onclick=e=>run(e.target,async()=>{await saveOutput();const a=document.createElement('a');a.href=`/workshops/${id}/export`;a.download='knowledge-workshop.md';a.click();});$('#delete-workshop').onclick=e=>run(e.target,async()=>{if(!confirm('Delete this saved workshop and its output?'))return;await api('/workshops/'+id,{method:'DELETE'});state.workshop=null;state.dirty=false;$('#workshop-detail').innerHTML='<h2>Workshop deleted</h2>';await loadWorkshops();});}
async function saveOutput(){state.workshop=await api('/workshops/'+state.workshop.id,{method:'PATCH',body:JSON.stringify({content:$('#output-editor').value})});state.dirty=false;$('#save-state').textContent='Saved';await loadWorkshops();notice('Output saved.');}
window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue='';}});
run(null,loadLibraries);
