from contextlib import AbstractContextManager
from typing import Any, BinaryIO, Protocol
from pathlib import Path


class StateStore(Protocol):
    """Load and save a complete snapshot without interpreting domain records."""

    def load(self) -> dict[str, Any] | None: ...

    def save(self, state: dict[str, Any]) -> None: ...


class ArtifactStore(Protocol):
    """Local filesystem operations needed by source, text, and chunk artifacts."""

    def create_directory(self, path: Path) -> None: ...

    def write_text(self, path: Path, text: str) -> None: ...

    def read_text(self, path: Path) -> str: ...

    def exists(self, path: Path) -> bool: ...

    def open_binary_write(self, path: Path) -> AbstractContextManager[BinaryIO]: ...

    def replace(self, temporary: Path, destination: Path) -> None: ...

    def remove(self, path: Path) -> None: ...

    def materialize(self, path: Path) -> AbstractContextManager[Path]:
        """Yield a local path guaranteed usable only while the context is active."""
        ...
